import {
  AddressBook,
  BookOpen,
  Briefcase,
  Envelope,
  GitBranch,
  GithubLogo,
  LinkedinLogo,
  List,
  Moon,
  ReadCvLogo,
  RedditLogo,
  SpinnerGap,
  StackOverflowLogo,
  Sun,
  Translate,
  UserFocus,
  X,
  XLogo,
} from "@phosphor-icons/react/dist/ssr";

export const icons = {
  AddressBook: <AddressBook />,
  BookOpen: <BookOpen />,
  Briefcase: <Briefcase />,
  Envelope: <Envelope />,
  GitBranch: <GitBranch />,
  GithubLogo: <GithubLogo />,
  LinkedinLogo: <LinkedinLogo />,
  List: <List />,
  Moon: <Moon />,
  ReadCvLogo: <ReadCvLogo />,
  RedditLogo: <RedditLogo />,
  SpinnerGap: <SpinnerGap />,
  StackOverflowLogo: <StackOverflowLogo />,
  Sun: <Sun />,
  Translate: <Translate />,
  UserFocus: <UserFocus />,
  X: <X />,
  XLogo: <XLogo />,
};
